name: Notify Discussions on Release

on:
  release:
    types:
      - published

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Discussions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          body="A new version has been released. [Check it out here](${{ github.event.release.html_url }})."
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"$body\"}" \
            "https://api.github.com/repos/${{ github.repository }}/discussions/categories/bot-%E8%87%AA%E5%8A%A8%E6%8E%A8%E9%80%81/comments"
